\input texinfo  @c -*-texinfo-*-
@c %**start of header 
@setfilename oef-mode.info
@settitle Manuel oef-mode beta (french)
@documentencoding UTF-8
@documentlanguage fr_FR
@c %**end of header

@dircategory Languages
@direntry
* oef-mode: (oef-mode).    major mode for editing online exercise format (french manual)
@end direntry

@c Mise à jour du manuel:
@c ---------------------
@c Effacer dir du répertoire oef-mode avant de faire un push vers Github
@c Générer le fichier info à partir du Terminal:
@c cd .emacs.d/el-get/oef-mode
@c makeinfo oef-mode.texi
@c Générer le fichier pdf à partir du Terminal:
@c texi2pdf oef-mode.texi 

@copying
This is the oef-mode manual, version beta (in french)
right @copyright{} 2017 - 2020 Raoul Hatterer.

OEF veut dire ''online exercise format'', un format pour des exercices interactifs destinés aux systèmes d'enseignement assisté par ordinateur. Le format d'un fichier OEF est très similaire à LaTeX. Il est composé d'instructions suivies d'un ou plusieurs paramètres. Le mode oef-mode a pour ambition d'être une solution efficace pour la création et la mise en ligne d'exercices sous ce format.
@end copying


@titlepage
@title oef-mode
@subtitle  mode majeur d'emacs pour éditer des exercices et des documents
@subtitle au format « online exercise format » (version beta du 30 janvier 2020)
@author Raoul Hatterer


@c The following two commands start the copyright page.
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@c Output the table of contents at the beginning.
@contents




@ifnottex
@node Top
@top Manuel d'utilisation d'oef-mode
@insertcopying
@end ifnottex

@menu 
* First Chapter::    The first chapter is the
                         only chapter in this sample.
* Index::            Complete index.
@end menu


@node First Chapter
@chapter First Chapter

@cindex chapter, first

This is the first chapter.
@cindex index entry, another

Here is a numbered list.

@enumerate
@item
This is the first item.

@item
This is the second item.
@end enumerate

@node Index
@unnumbered Index

@printindex cp
 



@c @node Top, , (dir), (dir)
@c @comment  node-name,  next,  previous,  up

@c top oef-mode User Manual

@c Ce manuel va vous expliquer comment utiliser le package oef-mode.


 

@c @menu
@c * Introduction::
@c * Installation:: Comment installer oef-mode
@c @end menu

@c @node Introduction, Installation, Top, Top
@c @comment  node-name,  next,  previous,  up
@c @chapter Introduction


@c @node Installation,  , Introduction, Top
@c @comment  node-name,  next,  previous,  up
@c @chapter Installation

@c @node Linux,  , Installation, Installation
@c @comment  node-name,  next,  previous,  up
@c @section Linux

@c If you want Emacs to load the file 'oef-mode.el' when it starts, put the file 'oef-mode.el'
@c in the dir "~/.emacs.d/lisp/", (create that directory if it doesn't exist).
@c By convention, the dir ~/.emacs.d/lisp/ is for packages you manually installed.
@c Then put the following in your Emacs init file "~/.emacs"
@c vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
@c  (add-to-list 'load-path "~/.emacs.d/lisp/") ;; Tell Emacs where is your personal elisp lib dir
@c  (load "oef") ;; load the packaged named oef (best not to include the ending “.el” or “.elc”)
@c ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
@c before the line (package-initialize).




@c @node MacOSX,  , Linux, Installation
@c @comment  node-name,  next,  previous,  up

@c @section MacOSX

@c * aquamacs (OSX):
@c If you want aquamacs to load the file 'oef-mode.el' when it starts, put the file 'oef-mode.el'
@c in the dir "~/Library/Preferences/Aquamacs Emacs/Packages/lisp/"
@c (create that directory if it doesn't exist).
@c Then put the following (without ;;) in your aquamacs init file
@c "~/Library/Preferences/Aquamacs Emacs/Preferences.el"
@c not in  ~/.emacs  witch is deprecated -- meaning 'should not be used for new installations,
@c but will continue to be supported' -- in Aquamacs on OS X)
@c vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
@c  (add-to-list 'load-path "~/Library/Preferences/Aquamacs Emacs/Packages/lisp/oef-mode/")
@c  ;Tell Emacs where is your personal elisp lib dir
@c  (load "oef-mode")
@c  ; load the packaged named oef-mode (best not to include the ending “.el” or “.elc”)
@c ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
@c before the line (package-initialize).

@c How to Debug Aquamacs if you need to:
@c Past the following command in a terminal:
@c /Applications/Aquamacs.app/Contents/MacOS/Aquamacs -nw --debug-init



@c @comment  node-name,  next,  previous,  up

@c @node Windows
@c @comment  node-name,  next,  previous,  up


@bye
