\input texinfo  @c -*-texinfo-*-
@c %**start of header 
@setfilename oef-mode.info
@settitle Manuel oef-mode version alpha (french)
@documentencoding UTF-8
@documentlanguage fr_FR
@c %**end of header

@dircategory Languages
@direntry
* oef-mode: (oef-mode).    major mode for editing online exercise format documents (french manual)
@end direntry

@c Mise à jour du manuel (développement):
@c -------------------------------------
@c Effacer "dir" du répertoire oef-mode avant de faire un push vers Github
@c Générer le fichier info à partir du Terminal OSX (ou du shell sous emacs mais pas  à partir de eshell):
@c cd .emacs.d/el-get/oef-mode
@c makeinfo oef-mode.texi
@c Générer le fichier pdf à partir du Terminal:
@c texi2pdf oef-mode.texi
@c Faire la mise à jour avec:
@c el-get-upate oef-mode
@c quitter puis relancer emacs

@c Insérer les commandes texinfo dans emacs:
@c -----------------------------------------
@c https://www.gnu.org/software/texinfo/manual/texinfo/html_node/Inserting.html

@copying
This is the @code{oef-mode} manual, version alpha (in french)

@quotation
OEF veut dire ''Online Exercise Format'', un format pour d'exercices et de documents interactifs destinés à l'enseignement assisté par ordinateur.

Le format d'un fichier OEF est très similaire à LaTeX. Il est composé d'instructions suivies d'un ou plusieurs paramètres. Le mode @code{oef-mode} pour Emacs a pour ambition d'être un outil efficace pour la création et la mise en ligne de documents ou d'exercices sous ce format.
@end quotation

Copyright @copyright{} 2017 - 2020 Raoul Hatterer.

@end copying


@titlepage
@title oef-mode
@subtitle  mode majeur d'Emacs pour éditer des exercices et des documents interactifs
@subtitle au format « online exercise format » (version alpha du 07 février 2021)
@author Raoul Hatterer


@c The following two commands start the copyright page.
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@c Output the table of contents at the beginning.
@contents

@ifnottex
@node Top
@top Manuel d'utilisation d'oef-mode
@insertcopying
@end ifnottex

@menu
* Introduction::                Commencer
* Index::                       Index
@end menu

@c --------------------------------------------------------------------------------

@node Introduction
@chapter Introduction

Le présent manuel est disponible au format PDF, mais il est également intégré, une fois le package oef-mode installé, au système d'information d'Emacs accessible par le raccourci @kbd{C-h i}.  


@menu
* Résumé::                      Bref résumé de ce que permet oef-mode
* Installations::               Installer Emacs, el-get, use-package, oef-mode
* Activation::                  Comment activer oef-mode pour certains buffers
@end menu

@node Résumé
@section Résumé
@code{oef-mode} est un mode majeur permettant d'éditer des exercices et des documents au format « online exercise format ».     

Il propose un menu et des raccourcis permettant d'accéder aux commandes, fonctions, scripts... spécifiques au format OEF.

@node Installations
@section  Installations
@cindex installation


@node Installation d'emacs
@subsection Installation d'emacs
@cindex installation, emacs

Cette partie est à destination des lecteurs du document PDF qui, connaissant peut-être déjà Wims et le format OEF, souhaiteraient tester @command{oef-mode}. Ils trouveront ici des indications pour installer Emacs.

@c Suivre les explications données ici  @url{http://ergoemacs.org/emacs/which_emacs.html}
@menu
* Sous Windows::                Télécharger et installer la version Windows d'emacs
* Sous Mac OSX::                Télécharger et installer la version Mac d'emacs
* Sous Linux::                  Télécharger et installer la version Linux d'emacs
@end menu


@node Sous Windows
@subsubsection Sous Windows
@cindex installation, emacs, Windows

@itemize
@item Déterminez si votre Microsoft Wimdows est 32 ou 64 bits: pour cela, appuyez sur la touche @key{Window} ; commencez à taper ``Afficher le système d'exploitation exécuté par votre ordinateur'' dans la zone de recherche et sélectionnez ce choix.  Cela fait apparaître une fenêtre dans laquelle le type de système (32 ou 64 bits) est indiqué.
@item Rendez-vous ensuite à la page de téléchargement: @url{https://ftp.gnu.org/pub/gnu/emacs/windows/emacs-27/} et téléchargez l'installateur:
@itemize
@item @command{emacs-$VERSION-x86_64-installer.exe} si votre système d'exploitation est 64 bits
@item @command{emacs-$VERSION-i686-installer.exe} si votre système d'exploitation est 32 bits
@end itemize
@item Lancez le programme d'installation pour installer Emacs sur votre ordinateur.
@end itemize

@node Sous Mac OSX
@subsubsection Sous Mac OSX
@cindex installation, emacs, Mac, OSX

Sous mac OSX, vous pouvez installer la version que vous trouverez ici: @url{https://emacsformacosx.com}


@node Sous Linux
@subsubsection Sous Linux
@cindex installation, emacs, Linux
@command{sudo apt-get install emacs27}




@node Fichier d'initialisation
@subsection Fichier d'initialisation
@cindex initialisation, init

Le fichier d'initialisation est un fichier qu'Emacs charge lorsqu'il démarre. Il est utilisé pour personnaliser Emacs.

Sous Linux et Mac, par défaut, Emacs cherche le fichier d'initialisation aux emplacements suivants :

@itemize
@item @file{~/.emacs}
@item @file{~/.emacs.el}
@item @file{~/.emacs.d/init.el} (depuis 2010 il s'agit de l'emplacement à privilégier)
@end itemize

Sous Microsoft Windows:

@itemize
@item @file{%HOMEPATH%\AppData\Roaming\.emacs.d\init.el} (emplacement à privilégier)
@item @file{%HOMEPATH%\AppData\Roaming\.emacs}
@end itemize

@node Gestionnaires de packages
@subsection Gestionnaires de packages
@cindex gestionnnaire, package

Le paquet (package) @command{oef-mode} ne faisant pas partie des paquets pré-installés avec emacs, il vous faudra l'installer.
 De plus, @code{oef-mode} n'étant pas répertorié dans @emph{elpa}, le dépôt de packages accessible par défaut dans emacs, je recommande d'installer el-get @url{http://wikemacs.org/wiki/El-get} un gestionnaire de package alternatif car le package @code{oef-mode} s'y trouve répertorié. Pour cela, nous utiliserons un fichier d'initialisation chargé en tout premier appelé @file{early-init.el}. 


Dans Emacs saisir la commande @kbd{C-x C-f} @code{Find file:} @file{~/.emacs.d/early-init.el} (ou @file{%HOMEPATH%\AppData\Roaming\.emacs.d\early-init.el} sous Microsoft Windows) pour créer un nouveau buffer nommé @file{early-init.el} et placez y le code suivant (@kbd{C-y} permet de coller(yank) dans Emacs) destiné à installer le gestionnaire de package @code{el-get}: 

@cartouche
@lisp
(add-to-list 'load-path "~/.emacs.d/el-get/el-get")

(unless (require 'el-get nil 'noerror)
  (require 'package)
  (add-to-list 'package-archives
               '("melpa" . "http://melpa.org/packages/"))
  (package-refresh-contents)
  (package-initialize)
  (package-install 'el-get)
  (require 'el-get))

(add-to-list 'el-get-recipe-path "~/.emacs.d/el-get-user/recipes")
(el-get 'sync)
@end lisp
@end cartouche

@itemize
@item Sélectionner l'ensemble du code avec @kbd{C-x h}
@item Indenter le code avec @kbd{M-x:} @code{indent-region}
@item Sauvegardez avec @kbd{C-x C-s}
@item Quittez Emacs avec @kbd{C-x C-c}
@end itemize

Microsoft Windows:
@itemize
@item Lancez Emacs. Patientez le temps de l'installation de @code{el-get}. Quittez Emacs. Relancez Emacs.
@end itemize

Mac OSX:
@itemize
@item Lancez Emacs à partir du Terminal:

(@command{/Applications/Emacs.app/Contents/MacOS/Emacs &}).

@item Patientez le temps de l'installation de @code{el-get}. Quittez Emacs. Relancez Emacs.
@end itemize

@node Configurer le clavier du Mac
@subsection Configurer le clavier du Mac

Vous vous apercevrez que, par défaut, les deux touches @kbd{option} ont été configurées en touche Meta @kbd{M-} pour emacs ce qui fait que vous avez perdu l'accès aux accolades (@kbd{option parenthèse}), aux crochets (@kbd{option shift parenthèse}) et aux autres caractères auxquels vous aviez accès par le biais de la touche @kbd{option}.

Éditer le fichier d'initialisation (@samp{~/.emacs.d/init.el}) et rajouter les lignes suivantes qui permettent d'avoir la touche @kbd{option} de gauche qui agit comme @kbd{Meta} tandis que la touche @kbd{option} de droite reste inchangée pour pouvoir accéder à des caractères comme les accolades ou les crochets. 

Pour cela, tapez @kbd{C-x C-f} (c'est-à-dire @kbd{control} x suivi de @kbd{control} f) dans Emacs.

@command{Find file:} apparaît sous la fenêtre. Saisir @samp{~/.emacs.d/init.el} et valider.

Coller le code suivant, sans indentation:

@cartouche
@lisp
;; mac specific bindings
(setq mac-right-command-modifier nil ; cmd de droite = cmd
      mac-command-modifier nil ; cmd de gauche = cmd
      mac-option-modifier 'meta ; option de gauche = meta
      mac-right-option-modifier nil ; option de droite = car. spéciaux
      mac-control-modifier 'control ; control de gauche = control 
      ns-function-modifier 'hyper ; fn key = hyper
      ns-right-alternate-modifier nil); cette touche n'existe pas

;; INDENT-REGION on OSX 
(global-set-key (kbd "C-:") 'indent-region)

(load-library "iso-transl") ; pour avoir l’accent circonflexe

;; exec-path
(add-to-list 'exec-path "/usr/local/bin")

;; load-path
(add-to-list 'load-path "~/.emacs.d/lisp")

@end lisp
@end cartouche

Sauvegardez avec @kbd{C-x C-s} puis quitter Emacs (@kbd{C-x C-c}), relancez Emacs et vérifiez que vous pouvez avoir les accolades. 

Si un fichier @file{~/.emacs} a été créé dans votre dossier personnel, il faut l'effacer car il prend le pas sur le fichier @file{~/.emacs.d/init.el}. 



@node Installer oef-mode
@subsection Installer oef-mode



@itemize 




@item Créer ou éditer le fichier d'initialisation (@code{~/.emacs.d/init.el}) et rajouter les lignes suivantes qui permettent d'installer @code{oef-mode}, et @code{use-package},  s'ils ne le sont pas déjà:

@cartouche
@lisp
(setq my:el-get-packages
      '(cl-lib
	el-get
        oef-mode	
        use-package            
        ))

(el-get 'sync my:el-get-packages)

(use-package company
	     :ensure t
	     :config
(add-hook 'after-init-hook 'global-company-mode)
	     )
;; global activation of the unicode symbol completion 

;; Permet d’activer le mode oef-mode quand on visite les
;;fichiers avec l’extension .oef
(load "oef-mode.el")
@end lisp
@end cartouche


@item Quitter et relancer emacs
@end itemize


La dernière version @code{oef-mode} vient d'être installée. Pour faire des mise à jour dans le futur, il y a la commande @code{M-x:}  @command{el-get-update oef-mode}



@node Installer oef-mode manuellement
@subsection Installer oef-mode manuellement

Si vous utilisiez déjà Emacs, sans @code{el-get} ni @code{use-package}, une alternative est d'installer @code{oef-mode} manuellement:

@itemize
@item S'il n'existe pas encore, créer le répertoire @code{"~/.emacs.d/lisp/"}
@item Télécharger l'archive zip @url{https://github.com/raoulhatterer/oef-mode/archive/master.zip}, la décompresser dans le répertoire  @file{"~/.emacs.d/lisp/"}
@item Ajouter le code suivant à votre fichier @file{~/.emacs.d/init.el} ou @code{.emacs} avant la ligne @samp{(package-initialize)}.

@cartouche
@lisp
;; Tell emacs where is your personal elisp lib dir
(add-to-list 'load-path "~/.emacs.d/lisp/oef-mode")
(load "oef-mode.el") ;; load the package named oef-mode
@end lisp
@end cartouche

@item Quitter et relancer emacs. 
@end itemize


Par convention, le répertoire @file{"~/.emacs.d/lisp/"} est la destination des bibliothèques installées de façon manuelle.



@node Autres installations
@subsection Autres installations



@itemize
@item Les fichiers qu’on supprime dans emacs vont dans la corbeille du Mac

@cartouche
@lisp
;;; Les fichiers qu’on supprime dans emacs vont dans la corbeille
(use-package osx-trash
	     :ensure t
	     :config
             (osx-trash-setup)
             (setq delete-by-moving-to-trash t)
	     )
@end lisp
@end cartouche



@end itemize







@node Activation
@section  Activation

@itemize
@item Pour activer et déactiver le mode: @kbd{M-x: oef-mode}
@item Quand vous créez un fichier avec l'extension @code{.oef} le mode s'active automatiquement.
@end itemize






@c --------------------------------------------------------------------------------


@node Index
@unnumbered Index

@printindex cp
 




@bye
